### ISSUE TITLE
network-uri-2.6.0.2 release breaks GHC 6.12.3 support

### ISSUE THREAD

**Issue by peti** [haskell/network-uri#14]
According to http://hydra.cryp.to/build/790708/nixlog/1/raw, the symbol `void` is missing:

    Network/URI.hs:128:37:
        Module `Control.Monad' does not export `void'

Maybe `base-compat` can help mitigate this kind of issue without having to resort to CPP?

**Comment by cartazio** [comment]
using CPP does avoid bringing in more deps though

**Comment by hvr** [comment]
@peti out of curiosity, are there still GHC 6.12 users that benefit from GHC<7 support?

**Comment by peti** [comment]
@hvr, yes, I think so. Personally, I wouldn't go out of my way to support such an old compiler, but since the problem that caused the incompatibility is rather easy to fix, I think it's worthwhile to avoid breaking the 6.12.x build.

**Comment by ezrakilty** [comment]
OK. I'll try a CPP based solution today.

Thanks for the report.

Ezra


On Sun, May 3, 2015, at 11:42 AM, Peter Simons wrote:
> @hvr[1], yes, I think so. Personally, I wouldn't go out of my way to
> support such an old compiler, but since the problem that caused the
> incompatibility is rather easy to fix, I think it's worthwhile to
> avoid breaking the 6.12.x build.


> — Reply to this email directly or view it on GitHub[2].

>

--
Ezra e. k. Cooper ezrakilty@mailhaven.com



Links:

  1. https://github.com/hvr
  2. https://github.com/haskell/network-uri/issues/14#issuecomment-98520509

**Comment by ezrakilty** [comment]
@peti: Is there an easy way for me to use the automation at hydra.cryp.to to validate changes, without doing a release? I'm finding it hard to install 6.12 just now. The Travis build for network-uri doesn't currently do 6.12, although I could look into setting that up.

**Comment by ezrakilty** [comment]
I realized that the easy fix was to use "_ <- foo" instead of "void $ foo", so we don't have to use CPP or base-compat. peti@, if you have a way to validate that short of me doing another release, great. If not, I'll just do a release and I think then it will drop into your tool, yes?

**Comment by peti** [comment]
Yes, if the new version shows up on Hackage, then http://hydra.cryp.to/jobset/nixpkgs/haskell-updates will build it automatically within a hour or so. Unfortunately, there's no easy (automatic) way to test code from a repository; the whole thing is geared towards Hackage, really.

**Comment by ezrakilty** [comment]
OK, released 2.6.0.3. Please write in if that works or doesn't work.

**Comment by peti** [comment]
Every works as expected. Thank you very much for the quick fix.
