### ISSUE TITLE
Add Hashable instance.

### ISSUE THREAD

**Issue by dredozubov** [haskell/network-uri#17]
I see using URI's quite often as `HashMap` keys, so it seems reasonable to add `Hashable` instance to `URI`.

**Comment by dredozubov** [comment]
Not so sure if it is used in GHC. If that's the case than non-base dependency would not be an option and issue should be closed. Can someone clarify?

**Comment by ezrakilty** [comment]
Hi—to your second question, I believe you're asking whether Hashable is defined within the `base' package, and the answer is no. So, it would require an additional dependency and I think it's probably best not to do this.

OTOH, it should be easy to create a Hashable instance that simply converts the URI to a string and hashes that. Or, the hashable-generics package could perhaps be used to give a default implementation.

I'll close the issue for now.
