### ISSUE TITLE
Incorrect parsing of URIs without scheme and with port number

### ISSUE THREAD

**Issue by k0ral** [haskell/network-uri#19]
Here is a ghci session to demonstrate my point:

```
> parseURIReference "domain.org/" -- (1)
Just domain.org/
> let Just x = parseURIReference "domain.org:80/" -- (2)
> x
domain.org:80/
> uriAuthority x
Nothing
> uriScheme x
"domain.org:"
> uriPath x
"80/"
> parseURIReference "1domain.org:80/" -- (3)
Nothing
> parseURIReference "http://1domain.org:80/" -- (4)
Just http://1domain.org:80/
```

Clearly, the parser is trying to interpret everything before the `:` character as the URI scheme:
- case `(2)` succeeds, but actually interprets `domain.org` as the scheme, and `80/` as the path;
- case `(3)` fails because the first character of a scheme cannot be a digit.

It seems that the parser has trouble distinguishing between scheme and domain. Is this a known limitation, or a bug ?

**Comment by ezrakilty** [comment]
The package hews quite close to RFC 3986, and looking at it now, I don't think your examples are valid URI references, strictly speaking (see Section 4.2). The RFC offers a syntax for scheme-relative URIs, but it requires an initial //. And the following examples do work as I'd expect:

    > parseURIReference "//domain.org/" >>= uriAuthority
    Just (URIAuth {uriUserInfo = "", uriRegName = "domain.org", uriPort = ""})
    > parseURIReference "//domain.org:80/" >>= uriAuthority
    Just (URIAuth {uriUserInfo = "", uriRegName = "domain.org", uriPort = ":80"})
    > parseURIReference "//1domain.org:80/" >>= uriAuthority
    Just (URIAuth {uriUserInfo = "", uriRegName = "1domain.org", uriPort = ":80"})
    > parseURIReference "http://1domain.org:80/" >>= uriAuthority
    Just (URIAuth {uriUserInfo = "", uriRegName = "1domain.org", uriPort = ":80"})

**Comment by k0ral** [comment]
Unfortunately, a large amount of URIs in the wild are omitting the leading `//` together with the scheme. Even browsers sometimes don't bother with `//` in their address bar...

Following the RFC is paramount, no arguments there, but it would be nice to also have more lenient tools to deal with the unperfect real world.

**Comment by rasendubi** [comment]
It's not possible to fix the issue without breaking RFC 3986 conformity. I believe, it should be closed then.
