### ISSUE TITLE
URI queries should not include `?`

### ISSUE THREAD

**Issue by seagreen** [haskell/network-uri#29]
At least if I'm reading the diagram here right: https://tools.ietf.org/html/rfc3986#section-3

**Comment by seagreen** [comment]
Just saw the "we're in no-breaking-things mode" comment on the other issue. Feel free to close this, though you could also leave it up to prevent other people opening the same issue.

**Comment by ezrakilty** [comment]
Right: I think the query string should really include `?` but it's not worth breaking anybody to correct that now, alas.
