### ISSUE TITLE
Make revisions for older network-uri releases

### ISSUE THREAD

**Issue by phadej** [haskell/network-uri#62]
So cabal-install doesn't pick them with GHC-9.0.

In particular, it's only network-uri-2.6.3.0 which seems to need a revision:

```
                     9.0.1  8.10.3  8.8.4  8.6.5  8.4.4  8.2.2  8.0.2  7.10.3  7.8.4  7.6.3  7.4.2  7.2.2  7.0.4
network-uri-2.6.4.1  OK     OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
network-uri-2.6.4.0  OK     OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
network-uri-2.6.3.0  FAIL   OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
network-uri-2.6.2.0  NO-IP  NO-IP   OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK   
network-uri-2.6.1.0  OK     OK      OK     OK     OK     OK     OK     OK      OK     OK     OK     OK     OK  
```

**Comment by ezrakilty** [comment]
If I understand, you're saying that version network-uri-2.6.3.0 should be bumped to 2.6.3.1, with the latter specifying a bound on `base` such as `base < 4.16.0.0`, which would ensure that the latest 2.6.3.x package is never chosen under GHC? Or perhaps you can explain what you mean by "make revisions."

**Comment by ezrakilty** [comment]
Regarding `base`: The GHC 9.0.1 release notes indicated that base 4.16.0.0 was included with that compiler, but what I actually got was 4.15.0.0.

So it would seem that setting `base < 4.15.0.0` in the 2.6.3.x series would do what you want, would it?https://github.com/haskell/network-uri/pull/64

**Comment by phadej** [comment]
Revision is not a new version, i.e. **do not** make `2.6.3.1` release.

Revision is altering of metadata of already uploaded versions. https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md, see https://hackage.haskell.org/package/network-uri/maintain

I'm sure Hackage Trustees will provide more guidance, in https://github.com/haskell-infra/hackage-trustees

**Comment by ezrakilty** [comment]
Got it, thanks. I've updated the metadata on 2.6.3.0 to require base < 4.15.

**Comment by phadej** [comment]
Please make a revisions for 2.6.4.0 too, but this is fine now.

**Comment by ezrakilty** [comment]
@phadej Regarding 2.6.4.0 you're concerned about the failure of `Safe`, correct? Happy to do it, sure.
