### ISSUE TITLE
Dependency parsec method not exposed

### ISSUE THREAD

**Issue by KevinDaSilvaS** [haskell/network-uri#66]
Hi while compiling my project I get the error in parsec dependency

Text\Parsec\Prim.hs:203:5: error:
parsec             >     `fail' is not a (visible) method of class `Monad'
parsec             >     |
parsec             > 203 |     fail msg = parserFail msg

cabal file:
build-depends:       base >= 4.7 && < 5,
                       mongoDB,
                       text,
                       network-uri,
                       split

Using: stack

**Comment by ezrakilty** [comment]
Can you share a minimal example that reproduces the problem?

**Comment by KevinDaSilvaS** [comment]
Hi I was investigating the issue a lit bit more, and I'm not a hundred percent sure it was in network.uri maybe it's a conflict with other dependencies. I'll close this issue til I find out the real problem. Thanks for the reply!
